import Head from "next/head";
import { useTastes } from "src/hooks/useTastes";
import "src/styles/globals.css";

const App = ({ Component, pageProps }) => {
  const tastes = useTastes();
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} tastes={tastes} />
    </>
  );
};

export default App;
