import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Center } from "../components/center";
import { Grid } from "../components/grid";
import { Headline } from "../components/headline";

export default function Home() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Headline page="about" />
        <Center />
        <Grid />
      </main>
    </>
  );
}
